dependencies:
  - name: kgit.global_config.fetch_prune
  - name: kgit.global_config.fetch_prune_tags
  - name: kgit.global_config.pull_rebase
  - name: korbad.git.user_global_config
    tasks_from: ensure_global_git_ignore_file_has_line.yml