managed_git_workspace_directory_grandparent_directory_path: "{{ xdg_user_home_path }}"
managed_git_workspace_directory_parent_directory_name: managed_git_workspaces
managed_git_workspace_directory_parent_directory_path: "{{ managed_git_workspace_directory_grandparent_directory_path }}/{{ managed_git_workspace_directory_parent_directory_name }}"
managed_git_local_repo_directory_path: "{{ managed_git_workspace_directory_parent_directory_path }}/{{ managed_git_workspace_name }}"
